### ISSUE TITLE
ENH: Various ways to simplify adding / editing pages and controls

### ISSUE THREAD

**Issue by ba58smith** [JohnySeven/SKipper#2]
From 3-hour video chat btwn Jan and Butch on 1/18/2023:

- [x] 1. Add ability to copy - paste an entire page as a way to get started on a new page layout.
- [x] 2. Add "Move page up" and "Move page down" buttons, next to the page icon, to make it simple to re-order the pages.
- [x] 3. Add "Open page" button, too.
- [x] 4. Add "Hide page on this device" button, too.
- [x] 5. Add copy-paste ability for a single Control (like a gauge, etc.)
- [ ] 6. Add Page Templates, for starting a new page. Some Templates should be included in the program, but it should also be possible to save any page layout as a Template.
- [x] 7. Add "Styles" (I think we had a better word, but I forget what it was) for each type of Control. There should be a default Style included in the program, which the user can modify and save. It should also be possible to save any Control's details as a Style, to be used when creating new controls. Changing a Style will automatically change the details of every Control that's connected to that Style.
- [x] 8. Allow one page to be default when app is started
- [x] 9. Show user pages first

**Comment by JohnySeven** [comment]
Thanks, @ba58smith!

**Comment by JohnySeven** [comment]
5. is done in commit https://github.com/JohnySeven/SKipper/commit/aefce982e518b701c4cfbe8b4c0d1981f49ed209
7. is partially working, the feature is called default property values, I need some editor for default values in UI. Here is sample of default values for Label:
```
"Defaults": {
      "Label": {
        "DefaultValues": {
          "FontSize": "40"
        }
      }
    }
```

**Comment by JohnySeven** [comment]
Commit https://github.com/JohnySeven/SKipper/commit/1473ee8d4327fc03535b74912b1977d2ef70eb96 brings support for page order change via Up/down buttons.
![image](https://user-images.githubusercontent.com/11419953/223547946-01983434-fdbe-4d4c-b352-5b7e243e9ebd.png)

**Comment by JohnySeven** [comment]
![image](https://user-images.githubusercontent.com/11419953/223863528-247224af-e6f5-47f5-bce9-677d81ca38cf.png)
I've done little redesign of page list - shows just little dropdown menu with all commands like copy, delete and make as startup. Will see how that works on Android.

**Comment by JohnySeven** [comment]
![image](https://user-images.githubusercontent.com/11419953/224511441-0a3c59d8-efa6-4ab7-b755-d33cf24a4e51.png)
MainMenuItem class now supports SortOrder and is using it to add menu items sorted based on order.

**Comment by JohnySeven** [comment]
![image](https://user-images.githubusercontent.com/11419953/224512566-f14b82dd-6714-410a-86ec-885e1af43583.png)
Final user page UI for now :-)

**Comment by JohnySeven** [comment]
![Screenshot_20230311_224255.jpg](https://user-images.githubusercontent.com/11419953/224512864-e6cf4e6c-d237-4a86-9771-a0f3f811bf3d.jpg)

Tested the UI on the Phone and it does look good. @ba58smith your opinion?
Thanks

**Comment by ba58smith** [comment]
Looks good! What are the four icons under each one? X deletes the user page? Second one looks like "copy" or "duplicate"? What about the last two?

**Comment by JohnySeven** [comment]
@ba58smith sorry, I've missed this comment. All buttons with icons have tooltips (just hover over any button and tool tip text will appear).

![image](https://user-images.githubusercontent.com/11419953/228062064-b51999e1-38c9-4de1-83b9-fec5b5df9e4f.png)
For the buttons, here is latest UI screenshot.

So from left: Delete, Duplicate page, Show page on startup, Open page, Toggle page favorite - will be shown on main bar (left or bottom).

**Comment by JohnySeven** [comment]
I'm closing this as complete - regarding 8. Page tempaltes I've created new issue that will define page templates in detail, it's here https://github.com/JohnySeven/SKipper/issues/4
